USE crimewarehouse;

CREATE TABLE IF NOT EXISTS DIM_BARRIOS
(
  BARRIO_KEY  INT NOT NULL,
  BARRIO_DESC TEXT NOT NULL,
  PRIMARY KEY (BARRIO_KEY)
);

CREATE TABLE IF NOT EXISTS DIM_COMUNAS
(
  COMUNA_KEY  INT NOT NULL,
  COMUNA_DESC TEXT NOT NULL,
  PRIMARY KEY (COMUNA_KEY)
);

CREATE TABLE IF NOT EXISTS DIM_TIPO_DELITO
(
  TIPO_DELITO_KEY INT NOT NULL,
  TIPO_DELITO_DESC TEXT NOT NULL,
  PRIMARY KEY (TIPO_DELITO_KEY)
);

