USE crimewarehouse;

CREATE TABLE IF NOT EXISTS FCT_HECHOS
(
  CONTACTO_ID INT NOT NULL,
  FECHA DATE NOT NULL,
  FRANJA_HORARIA INT NOT NULL,
  TIPO_DELITO_KEY INT NOT NULL,
  LATITUD FLOAT NOT NULL,
  LONGITUD FLOAT NOT NULL,
  COMUNA_KEY INT NOT NULL,
  BARRIO_KEY INT NOT NULL,
  PRIMARY KEY (CONTACTO_ID),
  FOREIGN KEY (BARRIO_KEY) REFERENCES DIM_BARRIOS(BARRIO_KEY),
  FOREIGN KEY (COMUNA_KEY) REFERENCES DIM_COMUNAS(COMUNA_KEY),
  FOREIGN KEY (TIPO_DELITO_KEY) REFERENCES DIM_TIPO_DELITO(TIPO_DELITO_KEY)
);